### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by openSourcerer9000** [mapcomponents/react-map-components-maplibre#12]
Could we get some more context on this lib? Is this built on top of react-map-gl or is the API completely different? 

[This](https://mapcomponents.github.io/react-map-components-maplibre/?path=/docs/core-maplibremap--example-config) is really cool but looking through the "show code" code I can't see anything about how to add source, layer etc.

I've been searching for the best web map stack for a couple years now. React-map-gl looks promising but mapbox killed compatibility with CRA with 2.0, and I haven't been able to hack it to roll back mapbox gl or to use maplibre. 

Searching for a working example to fork with react-map-gl and maplibre brought me here, but I'm a bit skeptical. The get started sandbox hits a transpilation error, same as react-map-gl with mapbox 2.0. 

If this is the FOSS webmap framework we've all been waiting for, please let us know

**Comment by openSourcerer9000** [comment]
Ok, [this codesandbox](https://codesandbox.io/s/g3tgi?file=/src/App.js) got me up and running. Great work, this seems like a good start so far.

I took a look at the WhereGroup site and it seems the company invests heavily in open source projects. Before investing my time in this lib, can you please clarify if this library will always be free and open source? 

After watching mapbox close GL down after gaining some traction and getting forks removed from Github for "copyright infringment" (MapTiler), I don't want to get baited into having a troublesome dependency again. In my opinion, they would have been better off building their paid product on top of their open source lib like everyone else, rather than trying to reign back the project they already put out there.

**Comment by cioddi** [comment]
We have updated the Readme to give a better overview and increase accessibility.

This response is more aimed to anyone else who stumbles upon this resource since you seem to have figured it out by yourself.

Basically this project is aiming to provide good react bindings for MapLibre-gl.
The CodeSandBox is the easiest way to try it, other options are documented in the readme file.
