### ISSUE TITLE
Bug: MlSketchTool is not listed as dependency

### ISSUE THREAD

**Issue by hilmyveradin** [mapcomponents/react-map-components-maplibre#135]
@mapcomponents/react-maplibre version: 0.1.80

## Steps To Reproduce

1. Import MlSketchTool
2. Use it as component
3. It will shown that Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

Link to code example:
https://codesandbox.io/s/base-template-forked-p5y5sw?file=/src/App.js

## The current behavior
I can't import MlSketchTool, because It's not included in the react map libre dist

## The expected behavior
I can import MlSketchTool

**Comment by cioddi** [comment]
Thank you for the message, we will include the export in the next release.
Until then it is always possible to copy the component code into your project (probably required adjusting some import statements).

**Comment by cioddi** [comment]
fixed by https://github.com/mapcomponents/react-map-components-maplibre/commit/07117830cffd7832dc280b65e338fb2aa7614027
