### ISSUE TITLE
Geojson layer now causing infinite loop

### ISSUE THREAD

**Issue by openSourcerer9000** [mapcomponents/react-map-components-maplibre#136]
I see you guys have been busy adding components, so I wanted to get the latest version and try them out.

This is the only thing I changed in my project:
![image](https://github.com/mapcomponents/react-map-components-maplibre/assets/61931826/3c66aaf4-a9c6-4adb-9adb-89dbfc5c0b11)

And now it gets caught in an infinite loop, caused by geojson layer somewhere
![image](https://github.com/mapcomponents/react-map-components-maplibre/assets/61931826/cba7fdf4-50b8-4372-ad78-75f3d326fe3c)

**Comment by cioddi** [comment]
Can you post the current configuration of you MlGeoJsonLayer.
I have experienced the infinite loop in the past when the paint or layout props did not match the layer type. I have been thinking about adding automatic checks which would slow down the initialization of MlGeoJsonLayers but increase the tolerance for faulty configuration.

**Comment by cioddi** [comment]
I will close this issue for now.
Please provide an example, so we can reopen it and solve the issue.
