### ISSUE TITLE
Bug: cypress should be a devDependency 

### ISSUE THREAD

**Issue by dBitech** [mapcomponents/react-map-components-maplibre#161]
Cypress is not supported on all platforms, but is only required for development purposes.    Cypress & its associated modules should not be required in production code. 

@mapcomponents/react-maplibre version: 1.0.1

**Comment by cioddi** [comment]
You are correct, it is fixed in 1.0.2

While the cypress module should not end up in production code if not explicitly imported by the app (if tree shaking works) it also is not required in the dev environments of apps depending on this package.
