### ISSUE TITLE
Bug: Event handlers passed to `MlGeoJsonLayer` are not updated

### ISSUE THREAD

**Issue by andrejilderda** [mapcomponents/react-map-components-maplibre#179]
First, thanks for the work on this library!

I'm running into the issue that event handlers passed to `MlGeoJsonLayer` (and possibly other layers) are not properly updated. This occurs when for example an onClick-handler is passed to a `<MlGeoJsonLayer>` which contains a stateful value.

## Version
@mapcomponents/react-maplibre 1.0.5 (latest)

## Reproduction link:
https://codesandbox.io/p/sandbox/base-template-forked-ppjjjg?file=%2Fsrc%2FApp.js%3A275%2C13

## Steps To Reproduce

1. Open the provided [CodeSandbox link](https://codesandbox.io/p/sandbox/base-template-forked-ppjjjg?file=%2Fsrc%2FApp.js%3A275%2C13).
2. Open the browser console to observe logs.
3. Click on the red line (route) on the map.

## The current behavior

When clicking on the route (red line), the `state.zoom` value logged in the console remains `4` and does not reflect the updated zoom level.

## The expected behavior

When clicking on the route, the logged `state.zoom` value should reflect the updated zoom level (incremented by 1 from the previous value).

Additional notes:
- I didn't memoize the onClick-function on purpose. Memoizing also doesn't fix it.
- It is probably related to the logic here in [`useLayer.ts`](https://github.com/mapcomponents/react-map-components-maplibre/blob/787dcea8e54420ba89263561a4d8ea89d3cc37b5/src/hooks/useLayer.ts#L334C1-L345C35).

If you need more information, feel free to reach out!

---

EDIT: Removed comment regarding useEffect firing twice (which is [intended React behavior](https://github.com/facebook/react/issues/16295#issuecomment-610098654)).

**Comment by andrejilderda** [comment]
Fyi, state updates via `useState` is not causing the useEffect to be run twice. The state value inside the function remains outdated though:
https://codesandbox.io/p/sandbox/base-template-forked-j3ns6y?workspaceId=53e1a141-c935-4d70-910a-10c2ca5673f4

**Comment by cioddi** [comment]
Hi @andrejilderda,
thank you for raising the issue. We have been aware of this issue and it is fixed in the latest release 1.0.6 that was just released a few minutes ago.

**Comment by andrejilderda** [comment]
Awesome, thanks a lot!
