### ISSUE TITLE
package.json has invalid "main" entry

### ISSUE THREAD

**Issue by eins78** [mapcomponents/react-map-components-maplibre#92]
The package as published on npm can not be used in all environments because the `main` entry is pointing to a non-existing file.
If (manually) changed to have the same content as the `module` entry, it works as expected.

https://github.com/mapcomponents/react-map-components-maplibre/blob/c5dbd45d315af381e8c27cf275fa94574c316c35/package.json#L4

https://github.com/mapcomponents/react-map-components-maplibre/blob/c5dbd45d315af381e8c27cf275fa94574c316c35/package.json#L6

**Comment by cioddi** [comment]
@eins78 we have included the suggested adjustments in the latest release. I hope everything works fine with the setup now without the need of manually changing anything in the installed modules.
